### ISSUE TITLE
[MC 1.20.1] [Fabric] Getting error log sapm with Create installed.

### ISSUE THREAD

**Issue by Steven-OConnell** [4nner/IronChests#72]
I am receiving log spam under the “Fatal Error” category.

`[12:35:51] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "anner.ironchest.blocks.blockentities.CrystalChestEntity.method_11281(net.minecraft.class_2371)" because "blockEntity" is null
	at anner.ironchest.IronChestsClient.lambda$onInitializeClient$0(IronChestsClient.java:33) ~[IronChests-2.0.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.15.11-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]`
	
I have received multiple crash reports from other users that end with a few hundred entries of the aforementioned error right before the client hard crashing.
By that I mean the log literally ends with the error spam.

Here is a log from my end where you can see the error:
[MC_1.20.1.log](https://github.com/user-attachments/files/16418856/MC_1.20.1.log)
_You can ignore all the missing block warnings as the save being loaded is from a client that had more mods than the ones I was testing with._

MC Version - 1.20.1
Mod Loader - Fabric 0.15.11
Installed mods:
└ [Create Fabric](https://modrinth.com/mod/create-fabric/versions?l=fabric&g=1.20.1) 0.5.1-f Build 1417
└ [Fabric API](https://modrinth.com/mod/fabric-api) 0.92.2
└ [Indium](https://modrinth.com/mod/indium) 1.0.34
└ [Sodium](https://modrinth.com/mod/sodium/versions?l=fabric&g=1.20.1) 0.5.11
└ [Sodium Extra](https://modrinth.com/mod/sodium-extra/versions?l=fabric&g=1.20.1) 0.5.4
└ [Iron Chests](https://modrinth.com/mod/cyberanner-ironchest/versions?l=fabric&g=1.20.1) 2.0.2

**Comment by 4nner** [comment]
Issue related to how the Crystal Chest renders item inside. This has been reimplemented in #76. Earlier versions are no longer supported.

**Comment by 4nner** [comment]
Reopening this as I might backport a patched version in the near future.
