### ISSUE TITLE
Crash server in Minecraft Fabric 1.19.2

### ISSUE THREAD

**Issue by shierru** [4nner/IronChests#84]
The server/client crashes when opening any chest.

Crash report:
```Description: Exception in server tick loop

Stacktrace:
    java.lang.NoSuchFieldError: backgroundPainter
	at knot//io.github.cottonmc.cotton.gui.widget.WPanel.<init>(WPanel.java:28)
	at knot//io.github.cottonmc.cotton.gui.widget.WPanelWithInsets.<init>(WPanelWithInsets.java:12)
	at knot//io.github.cottonmc.cotton.gui.widget.WGridPanel.<init>(WGridPanel.java:18)
	at knot//io.github.cottonmc.cotton.gui.SyncedGuiDescription.<init>(SyncedGuiDescription.java:54)
	at knot//io.github.cyberanner.ironchests.screenhandlers.ChestScreenHandler.<init>(ChestScreenHandler.java:18)
	at knot//io.github.cyberanner.ironchests.blocks.blockentities.GenericChestEntity.createScreenHandler(GenericChestEntity.java:41)
	at knot//MC//net.minecraft.block.entity.LootableContainerBlockEntity.createMenu(LootableContainerBlockEntity.java:161)
	at knot//MC//net.minecraft.server.network.ServerPlayerEntity.openHandledScreen(ServerPlayerEntity.java:1040)
	at knot//MC//net.minecraft.block.ChestBlock.onUse(ChestBlock.java:207)
	at knot//MC//net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock.java:964)
	at knot//MC//net.minecraft.server.network.ServerPlayerInteractionManager.redirect$bfa000$carpet$activateWithOptionalCactus(ServerPlayerInteractionManager.java:3029)
	at knot//MC//net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager.java:338)
	at knot//MC//net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler.java:1145)
	at knot//MC//net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket.java:34)
	at knot//MC//net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket.java:8)
	at knot//MC//net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22)
	at knot//MC//net.minecraft.server.ServerTask.run(ServerTask.java:18)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157)
	at knot//MC//net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23)
	at knot//net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:776)
	at knot//net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:159)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131)
	at knot//net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:758)
	at knot//net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:752)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:140)
	at knot//net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:737)
	at knot//net.minecraft.server.MinecraftServer.handler$bcc000$carpet$modifiedRunLoop(MinecraftServer.java:6894)
	at knot//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base@17.0.11/java.lang.Thread.run(Thread.java:840)```

Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.1.0-13-amd64
	Java Version: 17.0.11, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium

**Comment by 4nner** [comment]
The crash is due to LibGUI, which is used to render the chest interface. Any version older than 1.21.11 is not currently supported.

**Comment by 4nner** [comment]
Reopening this as I might backport a patched version in the near future.
